// src/pages/books.jsx
import React from 'react';
import book1 from '../assets/images/books/book1.png';
import book2 from '../assets/images/books/book2.png';
import book3 from '../assets/images/books/book3.png';
import book4 from '../assets/images/books/book4.png';
import book5 from '../assets/images/books/book5.png';
import book6 from '../assets/images/books/book6.png';
import book7 from '../assets/images/books/book7.png';
import book8 from '../assets/images/books/book8.png';
import book9 from '../assets/images/books/book9.png';
import book10 from '../assets/images/books/book10.png';
import book11 from '../assets/images/books/book11.png';
import book12 from '../assets/images/books/book12.png';
import '../styles/books.css';

const booksData = [
  { id: 1, title: "Договориться можно обо всем", image: book1 },
  { id: 2, title: "Сиддхартха", image: book2 },
  { id: 3, title: "Договориться можно обо всем", image: book3 },
  { id: 4, title: "Сиддхартха", image: book4 },
  { id: 5, title: "Договориться можно обо всем", image: book5 },
  { id: 6, title: "Сиддхартха", image: book6 },
  { id: 7, title: "Договориться можно обо всем", image: book7 },
  { id: 8, title: "Сиддхартха", image: book8 },
  { id: 9, title: "Договориться можно обо всем", image: book9 },
  { id: 10, title: "Сиддхартха", image: book10 },
  { id: 11, title: "Договориться можно обо всем", image: book11 },
  { id: 12, title: "Сиддхартха", image: book12 },
];

const Books = () => {
  return (
    <div className="books-container">
      {/* Компонент 1 */}
      <div className="books-hero">
        <h1 className="books-title">Книги</h1>
        <div className="books-description">
          <p>Добро пожаловать в наш раздел, посвященный книгам! Здесь вы найдете тщательно отобранные произведения, которые стали основой наших обсуждений и вдохновением для каждого члена нашего книжного клуба. Мы стремимся делиться знаниями и эмоциями, которые книги могут подарить. На этой странице вы найдете карточки с любимыми книгами наших участников, включая краткие аннотации и мнения о каждой из них. Присоединяйтесь к нам в чтении и открывайте новые горизонты вместе!</p>
        </div>
      </div>

      {/* Компонент 2 */}
      <h2 className="books-program-title">Годовая программа книг</h2>

      {/* Компонент 3 */}
      <div className="books-grid">
        {booksData.map((book) => (
          <div key={book.id} className="book-card">
            <h3>{book.title}</h3>
            <img src={book.image} alt={book.title} />
          </div>
        ))}
      </div>
    </div>
  );
};

export default Books;

// src/app/pages/books/books.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MemberCardComponent } from '../components/member-card/member-card.component';

@Component({
  selector: 'app-books',
  standalone: true,
  imports: [MemberCardComponent, CommonModule],
  templateUrl: './books.component.html',
  styleUrl: './books.component.scss'
})
export class BooksComponent {
    members = [
        { year: 2021, name: 'Книга 1', photoUrl: 'assets/books/1.jpg' },
        { year: 2020, name: 'Книга 2', photoUrl: 'assets/books/1.jpg' },
        { year: 2019, name: 'Книга 3', photoUrl: 'assets/books/1.jpg' },
        { year: 2019, name: 'Книга 4', photoUrl: 'assets/books/1.jpg' },
      ];
}

<!-- Второй блок с названием параметра -->
<div class="parameter-block">
  <h3 class="parameter-title">(Книги)</h3>
</div>

<div class="text-block">
  <p>
    Добро пожаловать в наш раздел, посвященный книгам! Здесь вы найдете
    тщательно отобранные произведения, которые стали основой наших обсуждений и
    вдохновением для каждого члена нашего книжного клуба. Мы стремимся делиться
    знаниями и эмоциями, которые книги могут подарить. На этой странице вы
    найдете карточки с любимыми книгами наших участников, включая краткие
    аннотации и мнения о каждой из них. Присоединяйтесь к нам в чтении и
    открывайте новые горизонты вместе!
  </p>
</div>

<div class="cards-container">
  <!-- Пример использования компонента MemberCard -->
  <app-member-card
    *ngFor="let member of members"
    [year]="member.year"
    [name]="member.name"
    [photoUrl]="member.photoUrl"
  >
  </app-member-card>
</div>

<p class="footer-text">
  © 2011-2024 THE ORATOR CLUB | ООО «КЛУБ ОРАТОРОВ», ИНН 7725843515 / KLUB
  ORATOROV, OOO TIN 7725843515
</p>
