// src/pages/contacts.jsx
import React from 'react';
import group1 from '../assets/images/group1.png';
import contact1 from '../assets/images/contact1.png';
import contact2 from '../assets/images/contact2.png';
import tgIcon from '../assets/images/tg.png';
import instIcon from '../assets/images/inst.png';
import '../styles/contacts.css';

const Contacts = () => {
  return (
    <div className="contacts-container">
      {/* Компонент 1 - Герой */}
      <div className="contacts-hero">
        <div className="contacts-custom-rectangle">
          <h1 className="contacts-main-title">Контакты</h1>
        </div>
        <img src={group1} alt="Group" className="contacts-group-photo" />
      </div>

      {/* Компонент 2 */}
      <div className="contacts-intro">
        <p>Здесь вы найдете контактные данные для связи с нашим клубом. Пишите нам с вопросами или предложениями - мы будем рады помочь!</p>
      </div>

      {/* Компонент 3 */}
      <h2 className="contacts-leader">Главный ведущий клуба — Касаткин Михаил</h2>

      {/* Компонент 4 */}
      <div className="contacts-card">
        <img src={contact1} alt="Contact 1" className="contacts-main-photo" />
        <div className="contacts-socials">
          <img src={tgIcon} alt="Telegram" className="contacts-social-icon" />
          <img src={instIcon} alt="Instagram" className="contacts-social-icon" />
        </div>
      </div>

      {/* Компонент 5 */}
      <h2 className="contacts-leader">Распорядитель клуба — Крутов Артемий</h2>

      {/* Компонент 6 */}
      <div className="contacts-card">
        <img src={contact2} alt="Contact 2" className="contacts-main-photo" />
        <div className="contacts-socials">
          <img src={tgIcon} alt="Telegram" className="contacts-social-icon" />
          <img src={instIcon} alt="Instagram" className="contacts-social-icon" />
        </div>
      </div>
    </div>
  );
};

export default Contacts;

// src/app/pages/contacts/contacts.component.ts
import { Component } from '@angular/core';
import { HeaderComponent } from '../components/header/header.component';

@Component({
  selector: 'app-contacts',
  standalone: true,
  imports: [HeaderComponent],
  templateUrl: './contacts.component.html',
  styleUrl: './contacts.component.scss'
})
export class ContactsComponent {

}

<app-header></app-header>
<div class="parameter-block">
  <h3 class="parameter-title">(Контакты)</h3>
</div>

<div class="text-block">
  <p>
    Здесь вы найдете контактные данные для связи с нашим книжным клубом. Пишите
    нам с вопросами или предложениями — мы будем рады помочь!
  </p>
</div>

<div class="social-links-block">
  <h2 class="section-title">Главный ведущий клуба - Касаткин Михаил</h2>

  <div class="links-container">
    <img src="assets/logo/M.jpg" alt="Logo" class="left-image" />

    <div class="link-item">
      <span class="link-text">Ссылка на телеграм:</span>
      <button class="link-button">
        <img src="assets/logo/tg.png" alt="Telegram" class="link-icon" />
        <span>Telegram</span>
      </button>
    </div>

    <div class="link-item">
      <span class="link-text">Ссылка на инстаграм:</span>
      <button class="link-button">
        <img src="assets/logo/insta.png" alt="Instagram" class="link-icon" />
        <span>Instagram</span>
      </button>
    </div>
  </div>
</div>

<div class="social-links-block">
  <h2 class="section-title">Распорядитель клуба - Крутов Артемий</h2>

  <div class="links-container">
    <img src="assets/logo/A.jpg" alt="Logo" class="left-image" />

    <div class="link-item">
      <span class="link-text">Ссылка на телеграм:</span>
      <button class="link-button">
        <img src="assets/logo/tg.png" alt="Telegram" class="link-icon" />
        <span>Telegram</span>
      </button>
    </div>

    <div class="link-item">
      <span class="link-text">Ссылка на инстаграм:</span>
      <button class="link-button">
        <img src="assets/logo/insta.png" alt="Instagram" class="link-icon" />
        <span>Instagram</span>
      </button>
    </div>
  </div>
</div>

<p class="footer-text">
  © 2011-2024 THE ORATOR CLUB | ООО «КЛУБ ОРАТОРОВ», ИНН 7725843515 / KLUB
  ORATOROV, OOO TIN 7725843515
</p>
